### PR TITLE
Instance parameters parsing added for private API

### PR DESCRIPTION
**Pull request by SergeyKemaev**
Instance parameters parsing modified due to changes in server API.
Should be merged along with https://github.com/qubell/vermilion/pull/4576

### CODE REVIEW

**Comment by SergeyKemaev** [comment]
@vasichkin could you please review this?

**Comment by vasichkin** [comment]
We should be backward-compatible while client used for older versions.

**Comment by dmakhno** [comment]
Hotfix in #119, based on idea here.
@SergeyKemaev, thanks.

**Comment by SergeyKemaev** [comment]
@dmakhno thank you too

**Pull request closed without merging**
