### PR TITLE
More cli utilities

### PR DESCRIPTION
**Pull request by chemikadze**
- restore-env
  - list-orgs
  - list-envs
  - list-instances
  - show-instance-logs
  - and more!

Example output:
```
(.venv)chemikadze@MacBook-Pro-chemikadze:~/programming/contrib-python-qubell-client$ python -mqubell.cli --help
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...

Options:
  --tenant TEXT         Tenant url to use, QUBELL_TENANT by default
  --user TEXT           User to use, QUBELL_USER by default
  --password TEXT       Password to use, QUBELL_PASSWORD by default
  --organization TEXT   Organization to use, QUBELL_ORGANIZATION by default
  --debug / --no-debug  Debug mode, also QUBELL_LOG_LEVEL can be used.
  --help                Show this message and exit.

Commands:
  create-org
  export-app
  import-app
  init-ca
  list-apps
  list-envs
  list-instances
  list-orgs
  restore-env
(.venv)chemikadze@MacBook-Pro-chemikadze:~/programming/contrib-python-qubell-client$ python -mqubell.cli list-orgs
563234fd3004b83071549495 Nikolay - Personal Account
5632381730045a6df6b10473 lime-tests
5638c2603004e1e0e6f584fb myorg
5638c31c3004e1e0e6f58533 myorg2
5638c3283004e1e0e6f5856b myorg3
5638c3353004e1e0e6f585a3 myorg4
5638c40e3004e1e0e6f585db myorg5
5638c41a3004e1e0e6f58613 myorg6
563c88a830041be803922eff solr
(.venv)chemikadze@MacBook-Pro-chemikadze:~/programming/contrib-python-qubell-client$ python -mqubell.cli --organization solr list-envs
563c88a830041be803922f00 default FAILED
(.venv)chemikadze@MacBook-Pro-chemikadze:~/programming/contrib-python-qubell-client$ python -mqubell.cli --organization solr list-apps
563c88a830041be803922f10 (1/0/0/0/0/0) Secure Vault 2.0
563c88e430041be803922f12 (0/0/0/0/0/0) Resource Pool
563c892030041be803922f14 (0/0/0/0/0/0) Shared Instances Catalog
563c895c30041be803922f16 (1/0/0/0/0/0) Workflow Service
563c899830041be803922f18 (1/0/0/0/0/0) Cloud Account
563c89d430041be803922f1a (0/0/0/0/0/0) Amazon Account
563c8a2f30041be803922f40 (0/0/0/0/0/0) Solr Cloud Orig
563c8a2f30041be803922f43 (0/0/0/0/0/0) Zookeeper1
563c8a3630041be803922f49 (0/0/0/0/0/0) tomcat
563e57b4300410cee8c128cc (0/0/0/0/0/1) compute.Instance
563c8a3a30041be803922f52 (0/0/0/0/0/1) Solr Cloud
563c8a3b30041be803922f55 (0/0/0/0/0/0) Zookeeper
563c8a2f30041be803922f3d (0/0/0/0/0/0) Application Server1
563c8a3630041be803922f46 (0/0/0/0/0/2) Solr Genesis
563c8a3630041be803922f4c (0/0/0/0/0/0) zookeeper genesis
563c8a3a30041be803922f4f (0/0/0/0/0/0) Application Server
(.venv)chemikadze@MacBook-Pro-chemikadze:~/programming/contrib-python-qubell-client$ python -mqubell.cli --organization solr list-instances 'Secure Vault 2.0'
5644be063004df7b7b811385 Invisible Secure Vault 2.0 ACTIVE
```

contrib-python-qubell-client_ _bash_ _184x44_and_dev-platform__qubell__-_flowdock

### CODE REVIEW

**Comment by chemikadze** [comment]
contrib-python-qubell-client_ _bash_ _184x44_and_dev-platform__qubell__-_flowdock

**Comment by dmakhno** [comment]
cool
@chemikadze, is there way with pip make an "cli-alias"?
@vasichkin, let's keep it in develop branch too.

**Comment by chemikadze** [comment]
@dmakhno Yes it is, i just did not invented catchy name yet :) my options are `qubell` (always are familiar with it, but name is obsolete) and `nomi` (it's short and sounds better that full "tonomi").

**Comment by chemikadze** [comment]
@vasichkin @dmakhno note i've added some env management ops

**Comment by vasichkin** [comment]
@chemikadze , why don't you use syntax like (nomi OBJECT { COMMAND}):
nomi environment create
nomi env delete
nomi env del
nomi env (default command is show all, for example)
?

Good example is 'ip' linux command.

**Comment by chemikadze** [comment]
@vasichkin Yep, current naming looked ok while there we a few commands, but now it does not scale. Will do.

**Comment by vasichkin** [comment]
Merged separately and uploaded to pip

**Pull request closed without merging**
