### PR TITLE
Router is stored in platform, thread-safe Platform

### PR DESCRIPTION
**Pull request by dmakhno**

### CODE REVIEW

**Comment by vasichkin** [comment]
This should be carefully tested

**Comment by dmakhno** [comment]
@vasichkin,
> Bad name

fixed. Please try to comment into pr, when there is one commit, shouldn't be different. But Github experience differs.

**Comment by dmakhno** [comment]
> This should be carefully tested

@vasichkin, done on selenium component from bazaar, works as expected.

**Comment by vasichkin** [comment]
Please, run test-components against broadleaf-starter-kit, for example.
You have to reproduce main reason of this refactoring - running many copies of tests agains same environment.

**Comment by dmakhno** [comment]
> running many copies of tests agains same environment

this is not the reason of change

**Pull request merged**
